### ISSUE TITLE
Does it work? 

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/code-server-feedstock#2]
Hi @xhochy, 

I wanted to try this for quite some time - finally I have a few free minutes. Unfortunately for me it does not work, when I call `code-server` it simply calls nodejs but does not start the server. So I was wondering if the package is working at all. 

best, 

Jan

**Comment by xhochy** [comment]
No, it's not working at all at the moment, I'm trying to fix this locally but pushed it back some time. Maybe I can have a look tomorrow or next week.

**Comment by xhochy** [comment]
Fixed with #4, @jan-janssen please try again.

**Comment by jan-janssen** [comment]
@xhochy Thanks for the fix. I started running code-server on mybinder, in case you are interested: 
https://github.com/jan-janssen/code-server-example 

Btw. I also learned about https://theia-ide.org the project is not as big as code-server at the moment, but basically build on vs code just like code-server and at least it lists many of the big players as contributors. So maybe if you find some time you can also try to build a Conda package for theia as well. Otherwise I am going to give it a try on the weekend. 

Best regards, 

Jan

**Comment by xhochy** [comment]
We actually used Theia before code-server but switched to code-server as it was closer to the original VSCode. If you want to have Theia packaged, you need to do this on your own. `code-server` has taken quite some time as I needed to recompile nodejs several times.

**Comment by xhochy** [comment]
Also note that there is https://github.com/betatim/vscode-binder which also demonstrates the use of code-server and where this all started ;)
